# Generated by Django 3.0.6 on 2020-05-25 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='room',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='qr_app.Apartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='room',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='qr_app.Apartment'),
            preserve_default=False,
        ),
    ]
